name: create_badge
description: Create & push badge

inputs:
  github_token:
    required: true
    description: The github access token.
    default: ${{ github.token }}

  branch:
    required: true
    description: The branch to store badges on.
    default: gh-badges

  path:
    required: true
    description: The prefix for badge paths.

  name:
    required: true
    description: The name of the badge, used as the storage path.

  label:
    required: true
    description: The left label of the badge, usually static.

  label_color:
    required: true
    description: Hex or named color for the label.
    default: 555

  status:
    required: true
    description: The right status as the badge, usually based on results.

  color:
    required: true
    description: An array (comma separated) with hex or named colors of the badge value
      background. More than one creates gradient background.
    default: blue

  style:
    required: true
    description: Badge style; flat or classic.
    default: classic

  scale:
    required: false
    description: Set badge scale.
    default: 1

  gradient:
    required: false
    description: Badge gradient, as comma seperated list of hex codes.

runs:
  using: composite
  steps:
    - name: Checkout badges branch
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch }}

    - name: Make badge dir
      shell: bash
      run: mkdir -p badges/${{ inputs.path }}

    - name: Generate badge
      uses: jaywcjlove/generated-badges@v1.0.9
      with:
        output: badges/${{ inputs.path }}/${{ inputs.name }}.svg
        label: ${{ inputs.label }}
        labelColor: ${{ inputs.label_color }}
        status: ${{ inputs.status }}
        color: ${{ inputs.color }}
        style: ${{ inputs.style }}
        scale: ${{ inputs.scale }}
        gradient: ${{ inputs.gradient }}

    - name: Create badge commit
      shell: bash
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add badges/${{ inputs.path }}/${{ inputs.name }}.svg
        git commit -m "Add/Update badge" || true

    - name: Push badge commit
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.github_token }}
        branch: ${{ inputs.branch }}
        directory: badges

    - name: Checkout original branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
