name: do_tests
description: Setup python, install dependancies, run tests & upload to codecov

inputs:
  prefix:
    required: true
    description: The prefix to prepend to the codecov & badge file name

  deploy:
    required: false
    description: Use requirements.txt for pinned dependencies
    default: "false"

  marker:
    required: true
    description: The pytest marker to test

  python:
    required: true
    description: The python version to use

outputs:
  badge_name:
    description: The name to be given to the badge
    value: ${{ inputs.prefix }}_${{ inputs.python }}_${{ inputs.deploy }}_${{ inputs.marker }}.svg

  badge_svg:
    description: A SVG string for the test badge
    value: ${{ steps.generate-badge.outputs.svg }}

runs:
  using: composite
  steps:
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python }}

    - name: Install dependancies
      if: ${{ !inputs.deploy }}
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]

    - name: Install dependancies (deploy)
      if: ${{ inputs.deploy }}
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install .[dev] -r requirements.txt

    - name: Run tests with Pytest
      shell: bash
      run: pytest -m ${{ inputs.marker }}

    - name: Upload coverage to Codecov
      if: always()
      uses: codecov/codecov-action@v3
      with:
        name: ${{ inputs.prefix }}/${{ inputs.python }}/${{ inputs.deploy }}
        flags: ${{ inputs.marker }}
        files: cov.xml

    - name: Generate badge
      id: generate-badge
      if: always()
      uses: jaywcjlove/generated-badges@v1.0.9
      with:
        label: "tests"
        labelColor: ${{ inputs.label_color }}
        status: ${{ steps.tests.outcome == 'success' && 'passing' || 'failing' }}
        color: ${{ steps.tests.outcome == 'success' && 'green' || 'red' }}
