name: Docs CI

on:
  push:
    branches:
      # Add more branches here to publish docs from other branches
      - main
    tags:
      - "*"
  pull_request:

jobs:
  docs:
    runs-on: "ubuntu-latest"
    steps:
      - name: Avoid git conflicts when tag and branch pushed at same time
        if: startsWith(github.ref, 'refs/tags')
        run: sleep 60

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Pandoc
        run: sudo apt-get install pandoc

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      
      - name: Install dependancies
        run: |
          python -m pip install --upgrade pip
          pip install .[docs] -r requirements.txt

      - name: Cache tutorial dataset
        id: cache-tutorial-dataset
        uses: actions/cache@v3
        with:
          path: /tmp/I22 Tutorial Dataset/
          key: tutorial-dataset

      - name: Download tutorial dataset
        if: steps.cache-tutorial-dataset.outputs.cache-hit != 'true'
        run: |
          wget https://zenodo.org/record/2671750/files/I22%20Tutorial%20Dataset.zip -O /tmp/i22_dataset.zip
          unzip /tmp/i22_dataset.zip -d /tmp/

      - name: Build docs
        run: sphinx-build -EWT --keep-going docs build/html

      - name: Move to versioned directory
        # e.g. main or 0.1.2
        run: mv build/html ".github/pages/${GITHUB_REF##*/}"

      - name: Write versions.txt
        run: sphinx_rtd_theme_github_versions .github/pages

      - name: Publish Docs to gh-pages
        if: github.event_name == 'push'
        # We pin to the SHA, not the tag, for security reasons.
        # https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
        uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305 # v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .github/pages
          keep_files: true
