name: Link Check

on:
  workflow_dispatch:
  schedule:
    # Run weekly to check URL links still resolve
    - cron: "0 8 * * WED"

jobs:
  docs:
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10"]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install python packages
        uses: ./.github/actions/install_requirements
        with:
          python_version: "3.9"
          requirements_file: requirements-dev-3.x.txt
          install_options: -e .[docs]

      - name: Cache tutorial dataset
        id: cache-tutorial-dataset
        uses: actions/cache@v3
        with:
          path: /tmp/I22 Tutorial Dataset/
          key: tutorial-dataset

      - name: Download tutorial dataset
        if: steps.cache-tutorial-dataset.outputs.cache-hit != 'true'
        run: |
          wget https://zenodo.org/record/2671750/files/I22%20Tutorial%20Dataset.zip -O /tmp/i22_dataset.zip
          unzip /tmp/i22_dataset.zip -d /tmp/

      - name: Check links
        run: tox -e docs build -- -b linkcheck
