name: Link Check

on:
  schedule:
    # Run every Monday at 8am to check URL links still resolve
    - cron: "0 8 * * MON"

jobs:
  docs:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python: ["3.9"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Pandoc
        run: sudo apt-get install pandoc

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependancies
        run: |
          python -m pip install --upgrade pip
          pip install .[docs] -r requirements.txt

      - name: Download tutorial dataset
        run: |
          wget https://zenodo.org/record/2671750/files/I22%20Tutorial%20Dataset.zip -O /tmp/i22_dataset.zip
          unzip /tmp/i22_dataset.zip -d /tmp/

      - name: Build docs
        run: sphinx-build -EWT --keep-going docs build/html -b linkcheck
